/**
 * @file compiler.c
 * @author Devin Arena
 * @brief Compiles tokens generated by the scanner into opcodes for the VM.
 * @since 6/23/2022
 **/

#include <stdio.h>
#include <string.h>

#include "common.h"
#include "compiler.h"
#include "memory.h"
#include "scanner.h"

typedef struct {
  Token current;
  Token previous;
  bool hadError;
  bool panicMode;
} Parser;

typedef enum {
  PREC_NONE,
  PREC_ASSIGNMENT,  // =
  PREC_OR,          // or
  PREC_AND,         // and
  PREC_EQUALITY,    // == !=
  PREC_COMPARISON,  // < > <= >=
  PREC_TERM,        // + -
  PREC_FACTOR,      // * /
  PREC_UNARY,       // ! -
  PREC_CALL,        // . ()
  PREC_PRIMARY
} Precedence;

typedef void (*ParseFn)(bool canAssign);

typedef struct {
  ParseFn prefix;
  ParseFn infix;
  Precedence precedence;
} ParseRule;

typedef struct {
  Token name;
  int depth;
  bool isCaptured;
} Local;

typedef struct {
  uint8_t index;
  bool isLocal;
} Upvalue;

typedef enum {
  TYPE_FUNCTION,
  TYPE_METHOD,
  TYPE_INITIALIZER,
  TYPE_SCRIPT
} FunctionType;

typedef struct {
  struct Compiler* enclosing;
  ObjFunction* function;
  FunctionType type;

  Local locals[UINT8_COUNT];
  Upvalue upvalues[UINT8_COUNT];
  int localCount;
  int scopeDepth;
} Compiler;

typedef struct ClassCompiler {
  struct ClassCompiler* enclosing;
  bool hasSuperclass;
} ClassCompiler;

Parser parser;
Compiler* current = NULL;
ClassCompiler* currentClass = NULL;

/**
 * @brief Initializes the compiler by zeroing out its memory.
 *
 * @param compiler Compiler* a pointer to the compiler to initialize.
 */
static void initCompiler(Compiler* compiler, FunctionType type) {
  compiler->enclosing = (struct Compiler*)current;
  compiler->function = NULL;
  compiler->type = type;
  compiler->localCount = 0;
  compiler->scopeDepth = 0;
  compiler->function = newFunction();
  current = (Compiler*)compiler;

  if (type != TYPE_SCRIPT) {
    current->function->name =
        copyString(parser.previous.start, parser.previous.length);
  }

  Local* local = &current->locals[current->localCount++];
  local->depth = 0;
  local->isCaptured = false;
  if (type != TYPE_FUNCTION) {
    local->name.start = "this";
    local->name.length = 4;
  } else {
    local->name.start = "";
    local->name.length = 0;
  }
}

static Chunk* currentChunk() {
  return &current->function->chunk;
}

/**
 * @brief Shows an error message for the specified token and line number.
 *
 * @param token Token* the token to show the error message for.
 * @param message const char* the error message to show.
 */
static void errorAt(Token* token, const char* message) {
  if (parser.panicMode)
    return;

  fprintf(stderr, "[line %d] Error", token->line);

  if (token->type == TOKEN_EOF) {
    fprintf(stderr, " at end");
  } else if (token->type == TOKEN_ERROR) {
    // Nothing.
  } else {
    fprintf(stderr, " at '%.*s'", token->length, token->start);
  }

  fprintf(stderr, ": %s\n", message);
  parser.hadError = true;
}

/**
 * @brief Prints an error message at the current token and puts the parser in
 * panic mode.
 *
 * @param message const char* the error message to print.
 */
static void parseError(const char* message) {
  errorAt(&parser.current, message);
  parser.panicMode = true;
}

/**
 * @brief Advances the parser to the next token. If an error occurs, the parser
 * will stop parsing and emit a parse error.
 *
 */
static void advance() {
  parser.previous = parser.current;

  while (true) {
    parser.current = scanToken();
    if (parser.current.type != TOKEN_ERROR)
      break;

    parseError(parser.current.start);
  }
}

/**
 * @brief Checks for the specified token. If it is found, the parser will
 * advance to the next token. If not, the parser will emit a parse error.
 *
 * @param type TokenType the type of token to check for.
 * @param message const char* the error message to show.
 */
static void consume(TokenType type, const char* message) {
  if (parser.current.type == type) {
    advance();
    return;
  }

  parseError(message);
}

/**
 * @brief Checks if the current token has the specified type.
 *
 * @param type TokenType the type to check for.
 * @return bool true if the current token has the specified type.
 */
static bool check(TokenType type) {
  return parser.current.type == type;
}

/**
 * @brief Checks for the specified token type. If it is found, the parser will
 * advance to the next token.
 *
 * @param type TokenType the type of token to check for.
 * @return bool true if the current token has the specified type.
 */
static bool match(TokenType type) {
  if (!check(type))
    return false;
  advance();
  return true;
}

/**
 * @brief Handles the parser being in panic mode by skipping all tokens until
 * the start of a declaration.
 */
static void synchronize() {
  parser.panicMode = false;

  while (parser.current.type != TOKEN_EOF) {
    // if the last token was a semicolon, we also consider it to be the end of a
    // statement.
    if (parser.previous.type == TOKEN_SEMICOLON)
      return;

    // these tokens designate the start of a statement and therefore
    // (hopefully) the end of panic mode
    switch (parser.current.type) {
      case TOKEN_CLASS:
      case TOKEN_FUN:
      case TOKEN_VAR:
      case TOKEN_FOR:
      case TOKEN_IF:
      case TOKEN_WHILE:
      case TOKEN_PRINT:
      case TOKEN_RETURN:
        return;
      default:
        break;
    }

    advance();
  }
}

/**
 * @brief Helper for emitting an opcode. Writes the opcode or extra data to the
 * current chunk.
 *
 * @param byte byte the opcode to write
 */
static void emitByte(uint8_t byte) {
  writeChunk(currentChunk(), byte, parser.previous.line);
}

/**
 * @brief Helper for emitting two bytes.
 *
 * @param byte1 uint8_t the first byte to emit
 * @param byte2 uint8_t the second byte to emit
 */
static void emitBytes(uint8_t byte1, uint8_t byte2) {
  emitByte(byte1);
  emitByte(byte2);
}

/**
 * @brief Helper for emitting loop instructions.
 *
 * @param loopStart the address of the loop start
 */
static void emitLoop(int loopStart) {
  emitByte(OP_LOOP);

  int offset = currentChunk()->count - loopStart + 2;
  if (offset > UINT16_MAX) {
    parseError("Loop body too large.");
    return;
  }

  emitByte((offset >> 8) & 0xff);
  emitByte(offset & 0xff);
}

/**
 * @brief Helper for emitting a jump instruction. Creates two bytes for the
 * offset, then later sets them to the correct values.
 *
 * @param instruction uint8_t the instruction to emit
 * @return int the address of the instruction
 */
static int emitJump(uint8_t instruction) {
  emitByte(instruction);
  emitByte(0xff);
  emitByte(0xff);
  return currentChunk()->count - 2;
}

/**
 * @brief Helper for emitting a return instruction.
 */
static void emitReturn() {
  // for init function, we return this
  if (current->type == TYPE_INITIALIZER) {
    emitBytes(OP_GET_LOCAL, 0);
  } else {
    emitByte(OP_NULL);
  }

  emitByte(OP_RETURN);
}

/**
 * @brief Adds a Value to the list of constants in the current chunk. Returns
 * the index of the constant.
 *
 * @param value Value the constant to add
 * @return uint8_t the index of the constant
 */
static uint8_t makeConstant(Value value) {
  int constant = addConstant(currentChunk(), value);

  // Devin: should probably look into haing more than 255 constants in a chunk
  if (constant > UINT8_MAX) {
    parseError("Too many constants in one chunk.");
    return 0;
  }

  return (uint8_t)constant;
}

/**
 * @brief Helper for emitting a constant instruction.
 *
 * @param value Value the value to emit
 */
static void emitConstant(Value value) {
  emitBytes(OP_CONSTANT, makeConstant(value));
}

/**
 * @brief Patches the offset of a jump instruction to point to the correct
 * offset.
 *
 * @param offset int the correct offset to update.
 */
static void patchJump(int offset) {
  // 2 bytes for the jump offset.
  int jump = currentChunk()->count - offset - 2;

  if (jump > UINT16_MAX) {
    parseError("Too much code to jump over.");
    return;
  }

  currentChunk()->code[offset] = (jump >> 8) & 0xff;
  currentChunk()->code[offset + 1] = jump & 0xff;
}

/**
 * @brief Starts a new scope by increasing the scope depth.
 *
 */
static void beginScope() {
  current->scopeDepth++;
}

/**
 * @brief Ends the current scope by decreasing the scope depth and pops any
 * nonclosed locals.
 */
static void endScope() {
  current->scopeDepth--;

  while (current->localCount > 0 &&
         current->locals[current->localCount - 1].depth > current->scopeDepth) {
    if (current->locals[current->localCount - 1].isCaptured) {
      emitByte(OP_CLOSE_UPVALUE);
    } else {
      emitByte(OP_POP);
    }
    current->localCount--;
  }
}

/**
 * @brief Handles shutting down the compiler. Emits a return opcode.
 */
static ObjFunction* endCompiler() {
  emitReturn();
  ObjFunction* function = current->function;

#ifdef DEBUG_PRINT_CODE
  if (!parser.hadError) {
    disassembleChunk(currentChunk(), function->name != NULL
                                         ? function->name->chars
                                         : "<script>");
  }
#endif

  current = (Compiler*)current->enclosing;
  return function;
}

// RECURSIVE DESCENT

// these functions need forward declarations because they are recursive
static void expression();
static void statement();
static void declaration();
static void parsePrecedence(Precedence precedence);
static ParseRule* getRule(TokenType type);

// Helper methods

/**
 * @brief Helper for comparing two identifiers. Compares their string values
 * using memcmp.
 *
 * @param a Token* the first identifier
 * @param b Token* the second identifier
 * @return bool true if the identifiers are equal, false otherwise
 */
static bool identifiersEqual(Token* a, Token* b) {
  if (a->length != b->length)
    return false;
  return memcmp(a->start, b->start, a->length) == 0;
}

/**
 * @brief Helper method for creating a new identifier as a constant.
 *
 * @param name Token* the identifier to create a constant from
 * @return uint8_t the index of the constant
 */
static uint8_t identifierConstant(Token* name) {
  return makeConstant(OBJ_VAL(copyString(name->start, name->length)));
}

/**
 * @brief Helper method for computing the number of arguments for a function.
 *
 * @return uint8_t the number of arguments
 */
static uint8_t argumentList() {
  uint8_t argCount = 0;
  if (!check(TOKEN_RIGHT_PAREN)) {
    do {
      expression();
      if (argCount == 255) {
        parseError("Cannot have more than 255 arguments.");
      }
      argCount++;
    } while (match(TOKEN_COMMA));
  }
  consume(TOKEN_RIGHT_PAREN, "Expect ')' after arguments.");
  return argCount;
}

/**
 * @brief Helper for adding a local to the current compiler.
 *
 * @param name Token the name of the local
 */
static void addLocal(Token name) {
  if (current->localCount == UINT8_COUNT) {
    parseError("Too many local variables in function.");
    return;
  }
  Local* local = &current->locals[current->localCount++];
  local->name = name;
  local->depth = -1;
  local->isCaptured = false;
}

/**
 * @brief Attempts to resolve a local variable from the current scope. If the
 * variable is not found, returns -1.
 *
 * @param compiler Compiler* the compiler to search
 * @param name Token* the name of the local
 * @return int the index of the local, or -1 if not found
 */
static int resolveLocal(Compiler* compiler, Token* name) {
  for (int i = compiler->localCount - 1; i >= 0; i--) {
    Local* local = &compiler->locals[i];
    if (identifiersEqual(name, &local->name)) {
      if (local->depth == -1) {
        parseError("Cannot read local variable in its own initializer.");
      }
      return i;
    }
  }

  return -1;
}

/**
 * @brief Adds an upvalue to the current compiler if it is not already added.
 *
 * @param compiler Compiler* the compiler to add the upvalue to
 * @param index the index of the upvalue
 * @param isLocal if the upvalue is a local
 * @return int the index of the upvalue
 */
static int addUpvalue(Compiler* compiler, uint8_t index, bool isLocal) {
  int upvalueCount = compiler->function->upvalueCount;

  for (int i = 0; i < upvalueCount; i++) {
    Upvalue* upvalue = &compiler->upvalues[i];
    if (upvalue->index == index && upvalue->isLocal == isLocal) {
      return i;
    }
  }

  if (upvalueCount == UINT8_COUNT) {
    parseError("Too many closure variables in function.");
    return 0;
  }

  compiler->upvalues[upvalueCount].isLocal = isLocal;
  compiler->upvalues[upvalueCount].index = index;
  return compiler->function->upvalueCount++;
}

/**
 * @brief Attempts to resovle the upvalue in the current compiler. If the
 * upvalue is not found, returns -1.
 *
 * @param compiler Compiler* the compiler to search
 * @param name Token* the name of the upvalue
 * @return int the index of the upvalue, or -1 if not found
 */
static int resolveUpvalue(Compiler* compiler, Token* name) {
  if (compiler->enclosing == NULL)
    return -1;
  int local = resolveLocal((Compiler*)compiler->enclosing, name);

  if (local != -1) {
    ((Compiler*)compiler->enclosing)->locals[local].isCaptured = true;
    return addUpvalue(compiler, (uint8_t)local, true);
  }

  int upvalue = resolveUpvalue((Compiler*)compiler->enclosing, name);
  if (upvalue != -1) {
    return addUpvalue(compiler, (uint8_t)upvalue, false);
  }

  return -1;
}

/**
 * @brief Declares a local variable if not in global scope. If the variable is
 * already declared, throws an error.
 */
static void declareVariable() {
  if (current->scopeDepth == 0)
    return;

  Token* name = &parser.previous;

  for (int i = current->localCount - 1; i >= 0; i--) {
    Local* local = &current->locals[i];
    if (local->depth != -1 && local->depth < current->scopeDepth)
      break;

    if (identifiersEqual(name, &local->name)) {
      parseError("Redefinition of variable in scope.");
    }
  }

  addLocal(*name);
}

/**
 * @brief Declares a variable and returns an index to its identifier constant.
 *
 * @param errorMessage const char* the error message to throw if no identifier
 * is found
 * @return uint8_t the index of the identifier
 */
static uint8_t parseVariable(const char* errorMessage) {
  consume(TOKEN_IDENTIFIER, errorMessage);

  declareVariable();
  if (current->scopeDepth > 0)
    return 0;

  return identifierConstant(&parser.previous);
}

/**
 * @brief Marks a variable as initialized by setting its depth.
 */
static void markInitialized() {
  if (current->scopeDepth == 0)
    return;
  current->locals[current->localCount - 1].depth = current->scopeDepth;
}

/**
 * @brief Defines a varible, marking it as initialized if its not a global,
 * otherwise just emit opcode for define global.
 *
 * @param variable uint8_t the index of the variable to define
 */
static void defineVariable(uint8_t variable) {
  if (current->scopeDepth > 0) {
    markInitialized();
    return;
  }
  emitBytes(OP_DEFINE_GLOBAL, variable);
}

/**
 * @brief Generates a synthetic token with the given text.
 *
 * @param text const char* the text of the token
 * @return Token Token the synthetic token
 */
static Token syntheticToken(const char* text) {
  Token token;
  token.start = text;
  token.length = (int)strlen(text);
  return token;
}

// Expressions

/**
 * @brief Descend through expression, parsing at assignment level precedence.
 */
static void expression() {
  parsePrecedence(PREC_ASSIGNMENT);
}

/**
 * @brief A base case for descent, parses the current token as a double
 * and creates a number constant from it.
 *
 * @param canAssign bool if the number can be assigned to (FALSE)
 */
static void number(bool canAssign) {
  double value = strtod(parser.previous.start, NULL);
  emitConstant(NUMBER_VAL(value));
}

/**
 * @brief A base case for descent, parses the current token as a string
 * and creates an object constant from it.
 *
 * @param canAssign bool if the string can be assigned to (FALSE)
 */
static void string(bool canAssign) {
  emitConstant(OBJ_VAL(
      copyString(parser.previous.start + 1, parser.previous.length - 2)));
}

/**
 * @brief A base case for descent, parses the current token as a literal
 * and emits the opcode for it.
 *
 * @param canAssign bool if the literal can be assigned to (FALSE)
 */
static void literal(bool canAssign) {
  switch (parser.previous.type) {
    case TOKEN_FALSE:
      emitByte(OP_FALSE);
      break;
    case TOKEN_NULL:
      emitByte(OP_NULL);
      break;
    case TOKEN_TRUE:
      emitByte(OP_TRUE);
      break;
    default:
      return;
  }
}

/**
 * @brief Helper for handling a variable. Determines what type of variable
 * it is and emits the proper opcodes for setting and getting it.
 *
 * @param name Token the name of the variable
 * @param canAssign bool if the variable can be assigned to
 */
static void namedVariable(Token name, bool canAssign) {
  printf("namedVariable: %.*s\n", name.length, name.start);
  uint8_t getOp, setOp;
  int arg = resolveLocal(current, &name);

  if (arg != -1) {
    getOp = OP_GET_LOCAL;
    setOp = OP_SET_LOCAL;
  } else if ((arg = resolveUpvalue(current, &name)) != -1) {
    getOp = OP_GET_UPVALUE;
    setOp = OP_SET_UPVALUE;
  } else {
    arg = identifierConstant(&name);
    getOp = OP_GET_GLOBAL;
    setOp = OP_SET_GLOBAL;
  }

  if (canAssign && match(TOKEN_EQUAL)) {
    expression();
    emitBytes(setOp, (uint8_t)arg);
  } else {
    emitBytes(getOp, (uint8_t)arg);
  }
}

/**
 * @brief Helper for getting a variable based on the previous token.
 *
 * @param canAssign bool if the variable can be assigned to
 */
static void variable(bool canAssign) {
  namedVariable(parser.previous, canAssign);
}

/**
 * @brief A base case for descent, parses the current token as a unary operator
 * and emits the opcode for it.
 *
 * @param canAssign bool if the operator can be assigned to (FALSE)
 */
static void unary(bool canAssign) {
  TokenType operatorType = parser.previous.type;

  parsePrecedence(PREC_UNARY);

  switch (operatorType) {
    case TOKEN_BANG:
      emitByte(OP_NOT);
      break;
    case TOKEN_MINUS:
      emitByte(OP_NEGATE);
      break;
    default:
      return;
  }
}

/**
 * @brief Base case for descent, parses the current token as a binary operator
 * and emits the opcode for it.
 *
 * @param canAssign bool if the operator can be assigned to (FALSE)
 */
static void binary(bool canAssign) {
  TokenType operator= parser.previous.type;
  ParseRule* rule = getRule(operator);
  parsePrecedence((Precedence)(rule->precedence + 1));

  switch (operator) {
    case TOKEN_BANG_EQUAL:
      emitBytes(OP_EQUAL, OP_NOT);
      break;
    case TOKEN_EQUAL_EQUAL:
      emitByte(OP_EQUAL);
      break;
    case TOKEN_GREATER:
      emitByte(OP_GREATER);
      break;
    case TOKEN_GREATER_EQUAL:
      emitBytes(OP_LESS, OP_NOT);
      break;
    case TOKEN_LESS:
      emitByte(OP_LESS);
      break;
    case TOKEN_LESS_EQUAL:
      emitBytes(OP_GREATER, OP_NOT);
      break;
    case TOKEN_PLUS:
      emitByte(OP_ADD);
      break;
    case TOKEN_MINUS:
      emitByte(OP_SUBTRACT);
      break;
    case TOKEN_STAR:
      emitByte(OP_MULTIPLY);
      break;
    case TOKEN_SLASH:
      emitByte(OP_DIVIDE);
      break;
    default:
      return;
  }
}

/**
 * @brief Descent for and keyword, creates a jump instruction and patches it.
 *
 * @param canAssign bool if the keyword can be assigned to (FALSE)
 */
static void and_(bool canAssign) {
  int endJump = emitJump(OP_JUMP_IF_FALSE);

  emitByte(OP_POP);
  parsePrecedence(PREC_AND);

  patchJump(endJump);
}

/**
 * @brief Descend for or keyword, creates a jump instruction and patches it.
 *
 * @param canAssign  bool if the keyword can be assigned to (FALSE)
 */
static void or_(bool canAssign) {
  int endJump = emitJump(OP_JUMP_IF_TRUE);

  emitByte(OP_POP);
  parsePrecedence(PREC_OR);

  patchJump(endJump);
}

/**
 * @brief Helper method for function calls. Gets the number of arguments
 * and emits the proper opcodes for function call.
 *
 * @param canAssign bool if the function call can be assigned to (FALSE)
 */
static void call(bool canAssign) {
  uint8_t argCount = argumentList();
  emitBytes(OP_CALL, argCount);
}

/**
 * @brief Descent for grouping, parentheses simply act as a wrapper around
 * an expression.
 *
 * @param canAssign bool if the grouping can be assigned to (FALSE)
 */
static void grouping(bool canAssign) {
  expression();
  consume(TOKEN_RIGHT_PAREN, "Expect ')' after expression.");
}

/**
 * @brief Descent case for binary dot operator. Allows getting and setting
 * fields and invoking methods.
 *
 * @param canAssign bool if the operator can be assigned to (FALSE)
 */
static void dot(bool canAssign) {
  consume(TOKEN_IDENTIFIER, "Expect property name after '.'.");
  uint8_t name = identifierConstant(&parser.previous);

  if (canAssign && match(TOKEN_EQUAL)) {
    expression();
    emitBytes(OP_SET_PROPERTY, name);
  } else if (match(TOKEN_LEFT_PAREN)) {
    uint8_t argCount = argumentList();
    emitBytes(OP_INVOKE, name);
    emitByte(argCount);
  } else {
    emitBytes(OP_GET_PROPERTY, name);
  }
}

/**
 * @brief Descent case for super keyword. Handles getting properties and
 * invoking methods of superclass.
 *
 * @param canAssign bool if the keyword can be assigned to (FALSE)
 */
static void super_(bool canAssign) {
  if (currentClass == NULL) {
    parseError("Can't use 'super' outside of a class.");
  } else if (!currentClass->hasSuperclass) {
    parseError("Can't use 'super' in a class with no superclass.");
  }
  consume(TOKEN_DOT, "Expect '.' after 'super'.");
  consume(TOKEN_IDENTIFIER, "Expect superclass method name.");
  uint8_t name = identifierConstant(&parser.previous);

  namedVariable(syntheticToken("this"), false);
  if (match(TOKEN_LEFT_PAREN)) {
    uint8_t argCount = argumentList();
    namedVariable(syntheticToken("super"), false);
    emitBytes(OP_SUPER_INVOKE, name);
    emitByte(argCount);
  } else {
    namedVariable(syntheticToken("super"), false);
    emitBytes(OP_SUPER_GET, name);
  }
}

/**
 * @brief Gets the instance of this assigned to the current class.
 *
 * @param canAssign bool if the keyword can be assigned to (FALSE)
 */
static void this_(bool canAssign) {
  if (currentClass == NULL) {
    parseError("Cannot use 'this' outside of a class.");
    return;
  }
  variable(false);
}

ParseRule rules[] = {
    [TOKEN_LEFT_PAREN] = {grouping, call, PREC_CALL},
    [TOKEN_RIGHT_PAREN] = {NULL, NULL, PREC_NONE},
    [TOKEN_LEFT_BRACE] = {NULL, NULL, PREC_NONE},
    [TOKEN_RIGHT_BRACE] = {NULL, NULL, PREC_NONE},
    [TOKEN_COMMA] = {NULL, NULL, PREC_NONE},
    [TOKEN_DOT] = {NULL, dot, PREC_CALL},
    [TOKEN_SEMICOLON] = {NULL, NULL, PREC_NONE},
    [TOKEN_BANG] = {unary, NULL, PREC_NONE},
    [TOKEN_BANG_EQUAL] = {NULL, binary, PREC_EQUALITY},
    [TOKEN_EQUAL] = {NULL, NULL, PREC_NONE},
    [TOKEN_EQUAL_EQUAL] = {NULL, binary, PREC_COMPARISON},
    [TOKEN_GREATER] = {NULL, binary, PREC_COMPARISON},
    [TOKEN_GREATER_EQUAL] = {NULL, binary, PREC_COMPARISON},
    [TOKEN_LESS] = {NULL, binary, PREC_COMPARISON},
    [TOKEN_LESS_EQUAL] = {NULL, binary, PREC_COMPARISON},
    [TOKEN_IDENTIFIER] = {variable, NULL, PREC_NONE},
    [TOKEN_STRING] = {string, NULL, PREC_NONE},
    [TOKEN_NUMBER] = {number, NULL, PREC_NONE},
    [TOKEN_AND] = {NULL, and_, PREC_AND},
    [TOKEN_CLASS] = {NULL, NULL, PREC_NONE},
    [TOKEN_ELSE] = {NULL, NULL, PREC_NONE},
    [TOKEN_FALSE] = {literal, NULL, PREC_NONE},
    [TOKEN_FOR] = {NULL, NULL, PREC_NONE},
    [TOKEN_FUN] = {NULL, NULL, PREC_NONE},
    [TOKEN_IF] = {NULL, NULL, PREC_NONE},
    [TOKEN_NULL] = {literal, NULL, PREC_NONE},
    [TOKEN_OR] = {NULL, or_, PREC_OR},
    [TOKEN_PRINT] = {NULL, NULL, PREC_NONE},
    [TOKEN_RETURN] = {NULL, NULL, PREC_NONE},
    [TOKEN_SUPER] = {super_, NULL, PREC_NONE},
    [TOKEN_THIS] = {this_, NULL, PREC_NONE},
    [TOKEN_TRUE] = {literal, NULL, PREC_NONE},
    [TOKEN_VAR] = {NULL, NULL, PREC_NONE},
    [TOKEN_WHILE] = {NULL, NULL, PREC_NONE},
    [TOKEN_ERROR] = {NULL, NULL, PREC_NONE},
    [TOKEN_EOF] = {NULL, NULL, PREC_NONE},
    [TOKEN_MINUS] = {unary, binary, PREC_TERM},
    [TOKEN_PLUS] = {NULL, binary, PREC_TERM},
    [TOKEN_SLASH] = {NULL, binary, PREC_FACTOR},
    [TOKEN_STAR] = {NULL, binary, PREC_FACTOR},
};

static ParseRule* getRule(TokenType type) {
  return &rules[type];
}

static void parsePrecedence(Precedence precedence) {
  advance();
  ParseFn prefixRule = getRule(parser.previous.type)->prefix;
  if (prefixRule == NULL) {
    parseError("Expect expression.");
    return;
  }

  bool canAssign = precedence <= PREC_ASSIGNMENT;
  prefixRule(canAssign);

  while (precedence <= getRule(parser.current.type)->precedence) {
    advance();
    ParseFn infixRule = getRule(parser.previous.type)->infix;
    infixRule(canAssign);
  }

  if (canAssign && match(TOKEN_EQUAL)) {
    parseError("Invalid assignment target.");
  }
}

static void block() {
  while (!check(TOKEN_RIGHT_BRACE) && !check(TOKEN_EOF)) {
    declaration();
  }

  consume(TOKEN_RIGHT_BRACE, "Expect '}' after block.");
}

static void function(FunctionType type) {
  Compiler compiler;
  initCompiler(&compiler, type);
  beginScope();

  consume(TOKEN_LEFT_PAREN, "Expect '(' after function name.");
  if (!check(TOKEN_RIGHT_PAREN)) {
    do {
      current->function->arity++;
      if (current->function->arity > 255) {
        parseError("Too many parameters (MAX=255).");
      }
      uint8_t constant = parseVariable("Expect parameter name.");
      defineVariable(constant);
    } while (match(TOKEN_COMMA));
  }

  consume(TOKEN_RIGHT_PAREN, "Expect ')' after parameters.");
  consume(TOKEN_LEFT_BRACE, "Expect '{' after function body.");

  block();

  ObjFunction* function = endCompiler();
  emitBytes(OP_CLOSURE, makeConstant(OBJ_VAL(function)));

  for (int i = 0; i < function->upvalueCount; i++) {
    emitByte(compiler.upvalues[i].isLocal ? 1 : 0);
    emitByte(compiler.upvalues[i].index);
  }
}

static void method() {
  consume(TOKEN_IDENTIFIER, "Expect method name.");
  uint8_t constant = identifierConstant(&parser.previous);

  FunctionType type = TYPE_METHOD;
  if (parser.previous.length == 4 &&
      memcmp(parser.previous.start, "init", 4) == 0) {
    type = TYPE_INITIALIZER;
  }
  function(type);
  emitBytes(OP_METHOD, constant);
}

static void classDeclaration() {
  consume(TOKEN_IDENTIFIER, "Expect class name.");
  Token className = parser.previous;
  uint8_t nameConstant = identifierConstant(&parser.previous);
  declareVariable();

  emitBytes(OP_CLASS, nameConstant);
  defineVariable(nameConstant);

  ClassCompiler classCompiler;
  classCompiler.enclosing = currentClass;
  currentClass = &classCompiler;

  if (match(TOKEN_LESS)) {
    consume(TOKEN_IDENTIFIER, "Expect superclass name.");
    variable(false);

    if (identifiersEqual(&parser.previous, &className)) {
      parseError("A class cannot inherit from itself.");
    }

    beginScope();
    addLocal(syntheticToken("super"));
    defineVariable(0);

    namedVariable(className, false);
    emitByte(OP_INHERIT);
    classCompiler.hasSuperclass = true;
  }

  namedVariable(className, false);
  consume(TOKEN_LEFT_BRACE, "Expect '{' before class body.");
  while (!check(TOKEN_RIGHT_BRACE) && !check(TOKEN_EOF)) {
    method();
  }
  consume(TOKEN_RIGHT_BRACE, "Expect '}' after class body.");
  emitByte(OP_POP);

  if (classCompiler.hasSuperclass) {
    endScope();
  }

  currentClass = currentClass->enclosing;
}

static void funDeclaration() {
  uint8_t global = parseVariable("Expect function name.");
  markInitialized();
  function(TYPE_FUNCTION);
  defineVariable(global);
}

static void varDeclaration() {
  uint8_t global = parseVariable("Expect variable name.");

  if (match(TOKEN_EQUAL)) {
    expression();
  } else {
    emitByte(OP_NULL);
  }

  consume(TOKEN_SEMICOLON, "Expect ';' after variable declaration.");

  defineVariable(global);
}

static void declaration() {
  if (match(TOKEN_CLASS)) {
    classDeclaration();
  } else if (match(TOKEN_FUN)) {
    funDeclaration();
  } else if (match(TOKEN_VAR)) {
    varDeclaration();
  } else {
    statement();
  }

  if (parser.panicMode) {
    synchronize();
  }
}

static void expressionStatement() {
  expression();
  consume(TOKEN_SEMICOLON, "Expect ';' after expression.");
  emitByte(OP_POP);
}

static void ifStatement() {
  consume(TOKEN_LEFT_PAREN, "Expect '(' after 'if'.");
  expression();
  consume(TOKEN_RIGHT_PAREN, "Expect ')' after condition.");

  int thenJump = emitJump(OP_JUMP_IF_FALSE);
  emitByte(OP_POP);
  statement();

  int elseJump = emitJump(OP_JUMP);

  patchJump(thenJump);
  emitByte(OP_POP);

  if (match(TOKEN_ELSE)) {
    statement();
  }

  patchJump(elseJump);
}

static void printStatement() {
  expression();
  consume(TOKEN_SEMICOLON, "Expect ';' after value.");
  emitByte(OP_PRINT);
}

static void returnStatement() {
  if (current->type == TYPE_SCRIPT) {
    parseError("Cannot return from top-level code.");
  }
  if (match(TOKEN_SEMICOLON)) {
    emitReturn();
  } else {
    if (current->type == TYPE_INITIALIZER) {
      parseError("Cannot return a value from an initializer.");
    }

    expression();
    consume(TOKEN_SEMICOLON, "Expect ';' after return value.");
    emitByte(OP_RETURN);
  }
}

static void whileStatement() {
  int loopStart = currentChunk()->count;
  consume(TOKEN_LEFT_PAREN, "Expect '(' after 'while'.");
  expression();
  consume(TOKEN_RIGHT_PAREN, "Expect ')' after condition.");

  int exitJump = emitJump(OP_JUMP_IF_FALSE);
  emitByte(OP_POP);
  statement();
  emitLoop(loopStart);

  patchJump(exitJump);
  emitByte(OP_POP);
}

static void forStatement() {
  beginScope();
  consume(TOKEN_LEFT_PAREN, "Expect '(' after 'for'.");

  if (match(TOKEN_SEMICOLON)) {
    // No initializer.
  } else if (match(TOKEN_VAR)) {
    varDeclaration();
  } else {
    expressionStatement();
  }

  int loopStart = currentChunk()->count;
  int exitJump = -1;
  if (!match(TOKEN_SEMICOLON)) {
    expression();
    consume(TOKEN_SEMICOLON, "Expect ';' after loop condition.");

    exitJump = emitJump(OP_JUMP_IF_FALSE);
    emitByte(OP_POP);
  }

  if (!match(TOKEN_RIGHT_PAREN)) {
    int bodyJump = emitJump(OP_JUMP);
    int incrementStart = currentChunk()->count;
    expression();
    emitByte(OP_POP);
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after for clauses.");

    emitLoop(loopStart);
    loopStart = incrementStart;
    patchJump(bodyJump);
  }

  statement();
  emitLoop(loopStart);

  if (exitJump != -1) {
    patchJump(exitJump);
    emitByte(OP_POP);
  }

  endScope();
}

static void statement() {
  if (match(TOKEN_PRINT)) {
    printStatement();
  } else if (match(TOKEN_IF)) {
    ifStatement();
  } else if (match(TOKEN_RETURN)) {
    returnStatement();
  } else if (match(TOKEN_WHILE)) {
    whileStatement();
  } else if (match(TOKEN_FOR)) {
    forStatement();
  } else if (match(TOKEN_LEFT_BRACE)) {
    beginScope();
    block();
    endScope();
  } else {
    expressionStatement();
  }
}

ObjFunction* compile(const char* source) {
  initScanner(source);
  Compiler compiler;
  initCompiler(&compiler, TYPE_SCRIPT);

  parser.hadError = false;
  parser.panicMode = false;

  advance();

  while (!match(TOKEN_EOF)) {
    declaration();
  }

  ObjFunction* function = endCompiler();
  return parser.hadError ? NULL : function;
}

void markCompilerRoots() {
  Compiler* compiler = current;
  while (compiler != NULL) {
    markObject((Obj*)compiler->function);
    compiler = (Compiler*)compiler->enclosing;
  }
}