
/**
 * @file compiler.c
 * @author Devin Arena
 * @brief Compiles tokens generated by the scanner into opcodes for the VM.
 * @since 6/23/2022
 **/

#include <stdio.h>

#include "compiler.h"

typedef struct {
    Token current;
    Token previous;
    bool hadError;
    bool panicMode;
} Parser;

typedef struct {
    Chunk* current;
} Compiler;

typedef enum {
  PREC_NONE,
  PREC_ASSIGNMENT,  // =
  PREC_OR,          // or
  PREC_AND,         // and
  PREC_EQUALITY,    // == !=
  PREC_COMPARISON,  // < > <= >=
  PREC_TERM,        // + -
  PREC_FACTOR,      // * /
  PREC_UNARY,       // ! -
  PREC_CALL,        // . ()
  PREC_PRIMARY
} Precedence;

typedef void (*ParseFn)(bool canAssign);

typedef struct {
    ParseFn prefix;
    ParseFn infix;
    Precedence precedence;
} ParseRule;

ParseRule rules[] = {
    [TOKEN_LEFT_PAREN] = {NULL, NULL, PREC_CALL},
    [TOKEN_RIGHT_PAREN] = {NULL, NULL, PREC_NONE},
    [TOKEN_LEFT_BRACE] = {NULL, NULL, PREC_NONE},
    [TOKEN_RIGHT_BRACE] = {NULL, NULL, PREC_NONE},
    [TOKEN_COMMA] = {NULL, NULL, PREC_NONE},
    [TOKEN_DOT] = {NULL, NULL, PREC_CALL},
    [TOKEN_SEMICOLON] = {NULL, NULL, PREC_NONE},
    [TOKEN_BANG] = {NULL, NULL, PREC_NONE},
    [TOKEN_BANG_EQUAL] = {NULL, NULL, PREC_EQUALITY},
    [TOKEN_EQUAL] = {NULL, NULL, PREC_NONE},
    [TOKEN_EQUAL_EQUAL] = {NULL, NULL, PREC_COMPARISON},
    [TOKEN_GREATER] = {NULL, NULL, PREC_COMPARISON},
    [TOKEN_GREATER_EQUAL] = {NULL, NULL, PREC_COMPARISON},
    [TOKEN_LESS] = {NULL, NULL, PREC_COMPARISON},
    [TOKEN_LESS_EQUAL] = {NULL, NULL, PREC_COMPARISON},
    [TOKEN_IDENTIFIER] = {NULL, NULL, PREC_NONE},
    [TOKEN_STRING] = {NULL, NULL, PREC_NONE},
    [TOKEN_NUMBER] = {NULL, NULL, PREC_NONE},
    [TOKEN_AND] = {NULL, NULL, PREC_AND},
    [TOKEN_ELSE] = {NULL, NULL, PREC_NONE},
    [TOKEN_FALSE] = {NULL, NULL, PREC_NONE},
    [TOKEN_FOR] = {NULL, NULL, PREC_NONE},
    [TOKEN_IF] = {NULL, NULL, PREC_NONE},
    [TOKEN_NULL] = {NULL, NULL, PREC_NONE},
    [TOKEN_OR] = {NULL, NULL, PREC_OR},
    [TOKEN_PRINT] = {NULL, NULL, PREC_NONE},
    [TOKEN_RETURN] = {NULL, NULL, PREC_NONE},
    [TOKEN_TRUE] = {NULL, NULL, PREC_NONE},
    [TOKEN_WHILE] = {NULL, NULL, PREC_NONE},
    [TOKEN_ERROR] = {NULL, NULL, PREC_NONE},
    [TOKEN_EOF] = {NULL, NULL, PREC_NONE},
    [TOKEN_MINUS] = {NULL, NULL, PREC_TERM},
    [TOKEN_PLUS] = {NULL, NULL, PREC_TERM},
    [TOKEN_SLASH] = {NULL, NULL, PREC_FACTOR},
    [TOKEN_STAR] = {NULL, NULL, PREC_FACTOR},
};

Parser parser;
Compiler* compiler;

/**
 * @brief Initializes the compiler by zeroing out its memory.
 *
 * @param compiler Compiler* a pointer to the compiler to initialize.
 */
static void initCompiler(Compiler* compiler, Chunk* chunk) {
  compiler->current = chunk;
}

/**
 * @brief Shows an error message for the specified token and line number.
 *
 * @param token Token* the token to show the error message for.
 * @param message const char* the error message to show.
 */
static void errorAtToken(Token* token, const char* message) {
  if (parser.panicMode)
    return;

  fprintf(stderr, "[line %d] Error", token->line);

  if (token->type == TOKEN_EOF) {
    fprintf(stderr, " at end");
  } else if (token->type == TOKEN_ERROR) {
    // Nothing.
  } else {
    fprintf(stderr, " at '%.*s'", token->length, token->start);
  }

  fprintf(stderr, ": %s\n", message);
  parser.hadError = true;
}

/**
 * @brief Prints an error message at the current token and puts the parser in
 * panic mode.
 *
 * @param message const char* the error message to print.
 */
static void parseError(const char* message) {
  errorAtToken(&parser.current, message);
  parser.panicMode = true;
}

/**
 * @brief Handles the parser being in panic mode by skipping all tokens until
 * the start of a declaration.
 *
 */
static void synchronize() {
  parser.panicMode = false;

  while (parser.current.type != TOKEN_EOF) {
    // if the last token was a semicolon, we also consider it to be the end of a
    // statement.
    if (parser.previous.type == TOKEN_SEMICOLON)
      return;

    // these tokens designate the start of a statement and therefore
    // (hopefully) the end of panic mode
    switch (parser.current.type) {
      case TOKEN_VOID:
      case TOKEN_INT:
      case TOKEN_DOUBLE:
      case TOKEN_FOR:
      case TOKEN_IF:
      case TOKEN_WHILE:
      case TOKEN_PRINT:
      case TOKEN_RETURN:
        return;
      default:
        break;
    }

    advance();
  }
}

/**
 * @brief Helper for emitting an opcode. Writes the opcode or extra data to the
 * current chunk.
 *
 * @param byte byte the opcode to write
 */
static void emitByte(uint8_t byte) {
  writeToChunk(compiler->current, byte, parser.previous.line);
}

/**
 * @brief Helper for emitting two bytes.
 *
 * @param byte1 uint8_t the first byte to emit
 * @param byte2 uint8_t the second byte to emit
 */
static void emitBytes(uint8_t byte1, uint8_t byte2) {
  emitByte(byte1);
  emitByte(byte2);
}

/**
 * @brief Helper for emitting a return opcode.
 */
static void emitReturn() {
  emitByte(OP_RETURN);
}

/**
 * @brief Advances the parser to the next token. If an error occurs, the parser
 * will stop parsing and emit a parse error.
 *
 */
static void advance() {
  parser.previous = parser.current;

  while (true) {
    parser.current = scanToken();

    if (parser.current.type != TOKEN_ERROR)
      break;

    parseError(parser.current.start);
  }
}

/**
 * @brief Handles shutting down the compiler. Emits a return opcode.
 */
static void endCompiler() {
  emitReturn();
}

// RECURSIVE DESCENT

static void expression();

static void expression() {

}

/**
 * @brief Compiles the source into opcodes for the VM to process.
 *
 * @param source const char* the source string to compile.
 * @param chunk Chunk* the chunk to compile opcodes into.
 * @return bool true if the compilation was successful, false otherwise.
 */
bool compile(const char* source, Chunk* chunk) {
  initScanner(source);
  initCompiler(compiler, chunk);

  parser.hadError = false;
  parser.panicMode = false;

  advance();

  while (parser.current.type != TOKEN_EOF) {
    expression();
  }

  endCompiler();
  return !parser.hadError;
}